improve configure and Makefile

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,4 +1,24 @@
 #!/usr/bin/env sh
+CPPFLAGS="-I../zlib -I../libpng -I../libwebp -I../libwebp/src $CPPFLAGS"
+if cd zlib; then
+	echo 'configuring zlib...'
+	./configure
+	echo 'configured zlib'
+	cd ..
+else
+	echo 'missing zlib!'
+	exit 1
+fi
+if cd libpng; then
+	echo 'configuring libpng...'
+	cp scripts/pnglibconf.h.prebuilt pnglibconf.h
+	./configure --enable-hardware-optimizations ac_cv_lib_z_zlibVersion=yes
+	echo 'configured libpng'
+	cd ..
+else
+	echo 'missing libpng!'
+	exit 1
+fi
 if cd libwebp; then
 	echo 'configuring libwebp...'
 	./autogen.sh
@@ -7,24 +27,5 @@ if cd libwebp; then
 	cd ..
 else
 	echo 'missing libwebp!'
-	exit 1
-fi
-if cd libpng; then
-	echo 'configuring libpng...'
-	cp scripts/pnglibconf.h.prebuilt pnglibconf.h
-	./configure
-	echo 'configured libpng'
-	cd ..
-else
-	echo 'missing libpng!'
-	exit 1
-fi
-if cd zlib; then
-	echo 'configuring zlib...'
-	./configure
-	echo 'configured zlib'
-	cd ..
-else
-	echo 'missing zlib!'
 	exit 1
 fi
